### ISSUE TITLE
vertical convolution

### ISSUE THREAD

**Issue by yufengwhy** [graytowne/caser_pytorch#1]
Any results about vertical convolution? Does it make a difference to the results?

**Comment by graytowne** [comment]
Yes there is a result in the [original paper](http://www.sfu.ca/~jiaxit/resources/wsdm18caser.pdf), the performance will drop if you don't use the vertical convolution. 
However, I didn't put a switch (turn on/off the vertical convolution) in this pytorch implementation. But you can try if you want by changing some codes in caser.py

**Comment by yufengwhy** [comment]
OK, sorry to miss the result in Table 3. 
Comparing to vertical convolution, the horizontal convolution makes little difference? If so, attention is a good choice.
Whatever, we can further this work from session basket.

**Comment by graytowne** [comment]
Yes, vertical convolution plays an very important role.
You can try and I'm looking forward for your results.
