### ISSUE TITLE
您好~或者您可以说一下您的天猫数据集处理时是改了代码嘛 ，我现在训练需要很久的时间，谢谢~

### ISSUE THREAD

**Issue by JunmeiHao** [graytowne/caser_pytorch#10]

**Comment by graytowne** [comment]
Hello, 关于tmall数据集，我印象里并没有改代码。如果你发现训练时间比较久的话可以用比较小一点的数据集并控制好hyper-parameter防止overfitting。
关于数据集因为tmall和foursquare并不是public available的（协议里说明了不可以散播）所以我没法给出处理好的dataset，关于gowalla你可以通过下面的链接：
https://github.com/graytowne/rank_distill/tree/master/datasets/gowalla

**Comment by JunmeiHao** [comment]
谢谢您！

在 2019-05-13 02:01:19，"Jiaxi Tang" <notifications@github.com> 写道：


Hello, �关于tmall数据集，我印象里并没有改代码。如果你发现训练时间比较久的话可以用比较小一点的数据集并控制好hyper-parameter防止overfitting。
关于数据集因为tmall和foursquare并不是public available的（协议里说明了不可以散播）所以我没法给出处理好的dataset，关于gowalla你可以通过下面的链接：
https://github.com/graytowne/rank_distill/tree/master/datasets/gowalla
