### ISSUE TITLE
关于代码结果的问题

### ISSUE THREAD

**Issue by DebonairLi** [graytowne/caser_pytorch#11]
您好，
我复现了您提供的代码，在ml1m上，结果如您所说，要比您原论文的结果要好。但是，对于gowalla，复现出的结果有点差（差距还不小）。我的做法是，下载了您rank_distill里的数据集，然后修改caser中的args，只修改了数据集，其他参数比如L,T都没有改。想问一下您是怎么做的？谢谢。

**Comment by graytowne** [comment]
hello 你好，
可以把其他的args也一起参考rank_distill修改一下，比较关键会影响performance的比如ac_conv,ac_fc,nv和nh

**Comment by DebonairLi** [comment]
好的，非常感谢，我再试一下！
