### ISSUE TITLE
如何处理foursquare和gowalla数据集？

### ISSUE THREAD

**Issue by DongZheng0030** [graytowne/caser_pytorch#12]
您好，foursquare和gowalla数据集中存在重复的签到数据，也就是说用户在同一个位置签到多次，请问您是如何处理这些重复数据的呢？是保留最早的一次签到记录还是最晚的一次？采用不同的处理方式对序列的影响较大，希望您提供帮助，非常感谢！

**Comment by graytowne** [comment]
你好，感谢你对我们工作的关注。对于重复的数据，为了能和non–sequential的方法公平比较，我做了去重（保留在sequence里的最后一次记录）。

**Comment by DongZheng0030** [comment]
您的工作非常有创意，并且很巧妙，非常感谢您的帮助！

**Comment by graytowne** [comment]
Closing this issue.
