### ISSUE TITLE
caser所使用的CNN建模属于item-level还是feature-level?

### ISSUE THREAD

**Issue by DebonairLi** [graytowne/caser_pytorch#13]
作者您好，
在看最近的一些文章里有引用您的论文，他们提到说caser属于item level的建模。我个人认为CNN的使用是对item的latent-feature的一个extract，所以个人觉得应该属于feature-level，我不知道我的理解对不对，恳请指教，谢谢！

**Comment by graytowne** [comment]
Hello你好，
说实话我不太清楚你说的item-level和feature-level分别代表什么，所以也没办法准确回答您的问题，不好意思。
