### ISSUE TITLE
Question about Sequential Intensity factor

### ISSUE THREAD

**Issue by miferroudjene** [graytowne/caser_pytorch#18]
Hello !
Just been curious, What sequential association rule mining algorithm you used to calculate the **Sequential Intensity** factor.
if you don't mined, it would be nice of you to share the code with me.

**Comment by anastasijamalyk** [comment]
Was having the same question actually, would be nice to check the code.

**Comment by graytowne** [comment]
Hi there, thanks for the interest in our paper! For the sequential intensity computation, I don't have a copy for the code now, sorry for that. While if I remember correctly, I followed the very standard FP-growth algorithm to get the support/confidence of rules, so it should be easy to implement that with some open sourced library for Frequent Pattern Mining.

Hope this answers your question, closing this issue for now. LMK if you have any further questions.
