### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by voladorlu** [graytowne/caser_pytorch#2]
I get a strange error after 40+ epoches, as it show below:

Traceback (most recent call last):
  File "train_caser.py", line 350, in <module>
    model.fit(train, test, verbose=False)
  File "train_caser.py", line 169, in fit
    negative_loss = -torch.mean(torch.log(1 - F.sigmoid(negative_prediction)))
RuntimeError: value cannot be converted to type double without overflow: -inf

**Comment by voladorlu** [comment]
@graytowne

**Comment by graytowne** [comment]
Hi @voladorlu,

This should because there are extreme values in 'negative_prediction',
you can add one single line of code before computing positive and negative losses to resolve this:
 <code>
negative_prediction = torch.clamp(negative_prediction, min=-10.0, max=10.0)
</code>
The code above could clip the values in 'negative_prediction' and should be helpful to avoid the overflow issue. Can you please check it?

**Comment by voladorlu** [comment]
Hi @graytowne 
It's a little strange that negative prediction turns to be a infinite value. Could you please check what's the reason? I can not target them easily.

**Comment by graytowne** [comment]
Hi @voladorlu 
Sorry I didn't have this issue before, if everything is ok on the MovieLens dataset, then the issue should come from your own dataset, you can take a check on that.

**Comment by voladorlu** [comment]
Hi @graytowne  Your suggested operation works fine on my own dataset. I guess the problem comes from the selection of l2 weight decay. The default value "1e-6" maybe fine for kernel parameters, but might be too weak for the embedding parameters, e.g. user feature vector, which are directly connected to the output layer. Anyway, thanks so much for sharing the code. It really means a lot to me.

**Comment by graytowne** [comment]
Hi @voladorlu 
In this case, you can use [http://pytorch.org/docs/master/optim.html#torch.optim.Optimizer.add_param_group](optimizer.add_param_group) to set different learning rate and l2 decay for different group of parameters.
Thanks, it is nice to hear our code actually make the help!
